language: php
php:
  - 5.4
before_script:
    - composer install --prefer-source
    - bin/composer install --prefer-source
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com